spring:
  application:
    name: bankingapp-transaction-service
  datasource:
    # url: jdbc:postgresql://${POSTGRES_SERVICE:localhost}:5432/bankingapp-account-service
    url: http://${POSTGRES_SERVICE:localhost}:5433/bankingapp-account-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: http://${KAFKA_SERVICE:localhost}:9092

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVICE:localhost}:8761/eureka
    registerWithEureka: true
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"