spring:
  application:
    name: bankingapp-gateway-service
  threads:
    virtual:
      enabled: true
  cloud.gateway.mvc:
    routesMap:
      configRoute1:
        uri: lb://bankingapp-account-service
        predicates:
          - Path=bankingapp/api/accounts/**
        filters:
#          - SetPath=/accounts
          - StripPrefix=2
      configRoute2:
        uri: lb://bankingapp-transaction-service
        predicates:
          - Path=bankingapp/api/transactions
        filters:
          - StripPrefix=2
          - CircuitBreaker=myCircuitBreaker
      configRoute3:
        uri: lb://bankingapp-fund-transfer-service
        predicates:
          - Path=bankingapp/api/fundtransfers
        filters:
          - StripPrefix=2

server:
  port: 8111

# Eureka Client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'