spring:
  application:
    name: bankingapp-fund-transfer-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE:localhost}:5433/bankingapp-account-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: http://${KAFKA_SERVICE:localhost}:9092

server:
  port: 8093

bankingapp:
  kafka:
    topic:
      fund-transfers: fund-transfer

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVICE:localhost}:8761/eureka
    registerWithEureka: true
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"